### ISSUE TITLE
Failed to build under FreeBSD 11.2

### ISSUE THREAD

**Issue by graemeg** [johalun/lwjgl3-port#1]
Hi. First off, thank you so much for trying to get Minecraft 1.13.x working under FreeBSD. I'm stuck at 1.12.2 until I can get this working - and really annoying that I have to dual boot into Linux just to try MC 1.13.x

Anyway, when it gets the the 'bx' part in the build.sh script, I get the following error.

```
[bx (freebsd)]$ tools/bin/bsd/genie 
/data/home/graemeg/temp/lwjgl3-port/bx/tools/bin/bsd/genie: Undefined symbol "stat@FBSD_1.5"
```

I'm assuming it is because I'm using FreeBSD 11.2 and you probably used FreeBSD 12? Or at least the 'genie' executable is for FreeBSD 12? This is why I think so...

```
[bx (freebsd)]$ file tools/bin/bsd/genie 
tools/bin/bsd/genie: ELF 64-bit LSB executable, x86-64, version 1 (FreeBSD), dynamically linked, interpreter /libexec/ld-elf.so.1, for FreeBSD 12.0 (1200084), FreeBSD-style, stripped

[bx (freebsd)]$ freebsd-version
11.2-RELEASE-p4
```

Any ideas where I could get a FreeBSD 11.2 compatible 'genie' executable, or how I can build it myself. I have no idea what genie is, so by the way. ;-)

**Comment by graemeg** [comment]
Further information. Seeing as I had Linux Emulation installed under FreeBSD 11.2 I thought I would give the linux binary of genie a go, and modified the makefile's to reference that instead. It seems to have worked and I managed to build 'bgfx', 'bimg', 'bx' and 'flfw'. It then failed building the actual 'lwjgl3' with the following error. What package or program includes the '**pkg-config**' executable?

![shot](https://user-images.githubusercontent.com/72053/47613257-a47c9880-da83-11e8-83c4-a5d7823aac8c.png)

**Comment by johalun** [comment]
Hi

Cool that the linux binary worked. I didn't think of trying that. If you want to build genie from source you can try the original repo https://github.com/bkaradzic/GENie

Are you missing the pkgconf package? 
```
johannes@jm:~ % pkg which /usr/local/bin/pkg-config
/usr/local/bin/pkg-config was installed by package pkgconf-1.5.3,1
```

**Comment by johalun** [comment]
By the way, how did you find this repo? :smiley:

**Comment by graemeg** [comment]
> Cool that the linux binary worked. I didn't think of trying that. If you want to build genie from source you can try the original repo https://github.com/bkaradzic/GENie

Thanks for the repo link. For now I don't seem to need it, but might just build a native version in case.

> Are you missing the pkgconf package?

Ah yes, that was missing. I didn't know which packages it belowed too. I've install it now and building lwjgl (the last part of your build.sh script) as we speak. Hopefully all goes well to the end now. :)

> By the way, how did you find this repo? :-)

I filed a bug report / feature request in LWJGL3 for FreeBSD support. Somebody there replied with your repo that I should try in the mean time. I also posted a message in the FreeBSD Forum, and they too referred me to your repo.

[edit]
lwjgl3 just completed compilation successfully. The moment of truth... does Minecraft 1.13.2 run. I'll let you know shortly.

**Comment by SamuelGogarty** [comment]
Im having the same issue as OP, i'm the one who attempted to build LWJGL3.2 on the FreeBSD forums. 
If I could get a copy of your makefile and steps to reproduce that would be neato.

**Comment by johalun** [comment]
I tried once running 1.13.2 but it wouldn't load. Let me know if you have more luck :)

**Comment by SamuelGogarty** [comment]
> I tried once running 1.13.2 but it wouldn't load. Let me know if you have more luck :)

not working for me, mainly because build.sh errors out on the following: 
`[100%] Built target alsoft-config
Cleaning...
../bx/tools/bin/bsd/genie --gcc=freebsd gmake
/usr/home/kaiser/lwjgl3-port/bx/tools/bin/bsd/genie: Undefined symbol "stat@FBSD_1.5"
gmake: *** [makefile:48: .build/projects/gmake-freebsd] Error 1
`

**Comment by graemeg** [comment]
Everything built fine with my last attempt, but when I run minecraft it still fails saying that it **can't find the liblwjgl.so** files. I did modify the ROOT variable in the minecraft-runtime-1.13 script. How am I supposed to launch Minecraft? I tried by running the minecraft-client-1.13 script, but I can't see anywhere where it runs on imports the minecraft-runtime-1.13 script. So maybe that is why the paths are not setup correctly for me, and the reason minecraft itself will not run. The launcher runs fine though.

**Comment by graemeg** [comment]
@SamuelGogarty : I use Johan's repo, but then modified the GENIE environment paths in the makefile's to not use $(OS), but hard-coded to /tools/bin/linux/genie. I was a stab in the dark, but seems to have worked because I have the Linux Emulation enabled in my FreeBSD 11.2 as well.

I modified bgfx, bimg and bx this way. All the lest was left as it was when I cloned the repo.

```
#GENIE=../bx/tools/bin/$(OS)/genie
GENIE=../bx/tools/bin/linux/genie
```

I also looked at the build.sh file and installed all the packages it mentioned on line 30 onwards. eg: **dyncall**, **assimp**, **gcc**, **gmake**, **cmake**, **apache-ant** and **pkgconf**.

**Comment by SamuelGogarty** [comment]
> Everything built fine with my last attempt, but when I run minecraft it still fails saying that it **can't find the liblwjgl.so** files. I did modify the ROOT variable in the minecraft-runtime-1.13 script. How am I supposed to launch Minecraft? I tried by running the minecraft-client-1.13 script, but I can't see anywhere where it runs on imports the minecraft-runtime-1.13 script. So maybe that is why the paths are not setup correctly for me, and the reason minecraft itself will not run. The launcher runs fine though.

did you redirect the default openjdk executable inside your minecraft profile settings to /usr/local/share/minecraft-client/minecract-runtime?

**Comment by johalun** [comment]
Except for running the script (on FreeBSD 12), what you have to do is to edit the profile in the launcher and change the executable to `[where you cloned this repo]/lwjgl3-port/minecraft-runtime-1.13`

**Comment by graemeg** [comment]
> You need to edit the profile in the minecraft launcher and change the executable to `[where you cloned this repo]/lwjgl3-port/minecraft-runtime-1.13`

Perfect! That worked a treat. Finally I have a working Minecraft 1.13.2 running on FreeBSD 11.2 :-D  Thanks for all your help.

@SamuelGogarty : Did you manage to get it working too? If you are running FreeBSD 11.2 64-bit, I could package up the compiled .so files if that might help.  As for your "Undefined symbol "stat@FBSD_1.5"" error you got - that is exactly what I got. I figure out it was the GENIE executable that was compiled for FreeBSD 12.0 and doesn't run under FreeBSD 11.2. So I used the Linux executabel - I haven't tried to compile my own GENIE executable yet, but will still do so at some point.

**Comment by johalun** [comment]
@graemeg Oh 1.13.2 is working too! I tried once before and it crashed. Tried again today and it works :)

**Comment by SamuelGogarty** [comment]
uhh not working for me
not sure what info i could supply to help

**Comment by SamuelGogarty** [comment]
> > You need to edit the profile in the minecraft launcher and change the executable to `[where you cloned this repo]/lwjgl3-port/minecraft-runtime-1.13`
> 
> Perfect! That worked a treat. Finally I have a working Minecraft 1.13.2 running on FreeBSD 11.2 :-D Thanks for all your help.
> 
> @SamuelGogarty : Did you manage to get it working too? If you are running FreeBSD 11.2 64-bit, I could package up the compiled .so files if that might help. As for your "Undefined symbol "stat@FBSD_1.5"" error you got - that is exactly what I got. I figure out it was the GENIE executable that was compiled for FreeBSD 12.0 and doesn't run under FreeBSD 11.2. So I used the Linux executabel - I haven't tried to compile my own GENIE executable yet, but will still do so at some point.

yeah if you could bundle it up for me that would be a great help, thanks.

**Comment by johalun** [comment]
@SamuelGogarty The readme has been updated to inform of potential traps. Please note that this is just an ugly hack to get things running until the official port has been updated. I am not the maintainer of any of these ports.

**Comment by graemeg** [comment]
@SamuelGogarty : I've archived the native FreeBSD 11.2 files. I hope I got all of them. You'll obviously have to tweak the runtime scrript to point to the correct location,  and modify the Minecraft launcher profile being used to reference that runtime (like @johalun  mentioned). If I missed something, just let me know, and I'll make a new archive available.

You can download the archive from this link:  http://geldenhuys.co.uk/~graemeg/minecraft_1.13.2_for_freebsd_11.2.tar.gz
