### ISSUE TITLE
Hi. I am having this issue.

### ISSUE THREAD

**Issue by LordBSD** [johalun/lwjgl3-port#3]
CMD IN: -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -Djava.library.path=/home/mike/minecraft/versions/1.13.2/1.13.2-natives-4836937302868 -Dminecraft.launcher.brand=java-minecraft-launcher -Dminecraft.launcher.version=1.6.89-j -cp /home/mike/minecraft/libraries/com/mojang/patchy/1.1/patchy-1.1.jar:/home/mike/minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar:/home/mike/minecraft/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar:/home/mike/minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar:/home/mike/minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar:/home/mike/minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar:/home/mike/minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar:/home/mike/minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar:/home/mike/minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar:/home/mike/minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar:/home/mike/minecraft/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar:/home/mike/minecraft/libraries/com/google/guava/guava/21.0/guava-21.0.jar:/home/mike/minecraft/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar:/home/mike/minecraft/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar:/home/mike/minecraft/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar:/home/mike/minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar:/home/mike/minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar:/home/mike/minecraft/libraries/com/mojang/brigadier/1.0.14/brigadier-1.0.14.jar:/home/mike/minecraft/libraries/com/mojang/datafixerupper/1.0.19/datafixerupper-1.0.19.jar:/home/mike/minecraft/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar:/home/mike/minecraft/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar:/home/mike/minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar:/home/mike/minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar:/home/mike/minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar:/home/mike/minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar:/home/mike/minecraft/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar:/home/mike/minecraft/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar:/home/mike/minecraft/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar:/home/mike/minecraft/libraries/com/mojang/realms/1.13.9/realms-1.13.9.jar:/home/mike/minecraft/libraries/org/lwjgl/lwjgl/3.1.6/lwjgl-3.1.6.jar:/home/mike/minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.1.6/lwjgl-jemalloc-3.1.6.jar:/home/mike/minecraft/libraries/org/lwjgl/lwjgl-openal/3.1.6/lwjgl-openal-3.1.6.jar:/home/mike/minecraft/libraries/org/lwjgl/lwjgl-opengl/3.1.6/lwjgl-opengl-3.1.6.jar:/home/mike/minecraft/libraries/org/lwjgl/lwjgl-glfw/3.1.6/lwjgl-glfw-3.1.6.jar:/home/mike/minecraft/libraries/org/lwjgl/lwjgl-stb/3.1.6/lwjgl-stb-3.1.6.jar:/home/mike/minecraft/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar:/home/mike/minecraft/versions/1.13.2/1.13.2.jar net.minecraft.client.main.Main --username embryocore --version 1.13.2 --gameDir /home/mike/.minecraft --assetsDir /home/mike/minecraft/assets --assetIndex 1.13.1 --uuid 60e83d817da04a1590a42700c3e294ec --accessToken a62be787e792433a80321cb672e31a51 --userType legacy --versionType release --width 854 --height 480
CMD OUT: -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -Djava.library.path=/home/mike/lwjgl3//native-libs:/home/mike/lwjgl3//lwjgl3/bin/libs/ -Dminecraft.launcher.brand=java-minecraft-launcher -Dminecraft.launcher.version=1.6.89-j -cp /home/mike/minecraft/libraries/com/mojang/patchy/1.1/patchy-1.1.jar:/home/mike/minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar:/home/mike/minecraft/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar:/home/mike/minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar:/home/mike/minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar:/home/mike/minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar:/home/mike/minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar:/home/mike/minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar:/home/mike/minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar:/home/mike/minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar:/home/mike/minecraft/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar:/home/mike/minecraft/libraries/com/google/guava/guava/21.0/guava-21.0.jar:/home/mike/minecraft/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar:/home/mike/minecraft/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar:/home/mike/minecraft/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar:/home/mike/minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar:/home/mike/minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar:/home/mike/minecraft/libraries/com/mojang/brigadier/1.0.14/brigadier-1.0.14.jar:/home/mike/minecraft/libraries/com/mojang/datafixerupper/1.0.19/datafixerupper-1.0.19.jar:/home/mike/minecraft/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar:/home/mike/minecraft/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar:/home/mike/minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar:/home/mike/minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar:/home/mike/minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar:/home/mike/minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar:/home/mike/minecraft/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar:/home/mike/minecraft/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar:/home/mike/minecraft/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar:/home/mike/minecraft/libraries/com/mojang/realms/1.13.9/realms-1.13.9.jar:/home/mike/lwjgl3//lwjgl3/bin/RELEASE/lwjgl/lwjgl.jar:/home/mike/minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.1.6/lwjgl-jemalloc-3.1.6.jar:/home/mike/lwjgl3//lwjgl3/bin/RELEASE/lwjgl-openal/lwjgl-openal.jar:/home/mike/lwjgl3//lwjgl3/bin/RELEASE/lwjgl-opengl/lwjgl-opengl.jar:/home/mike/lwjgl3//lwjgl3/bin/RELEASE/lwjgl-glfw/lwjgl-glfw.jar:/home/mike/lwjgl3//lwjgl3/bin/RELEASE/lwjgl-stb/lwjgl-stb.jar:/home/mike/minecraft/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar:/home/mike/minecraft/versions/1.13.2/1.13.2.jar net.minecraft.client.main.Main --username embryocore --version 1.13.2 --gameDir /home/mike/.minecraft --assetsDir /home/mike/minecraft/assets --assetIndex 1.13.1 --uuid 60e83d817da04a1590a42700c3e294ec --accessToken a62be787e792433a80321cb672e31a51 --userType legacy --versionType release --width 854 --height 480
OpenJDK 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
[16:21:48] [Client thread/INFO]: Setting user: embryocore
[16:21:49] [Client thread/INFO]: LWJGL Version: 3.2.1 SNAPSHOT
[16:21:49] [Client thread/INFO]: [STDERR]: [LWJGL] [ERROR] Incompatible Java and native library versions detected.
Possible reasons:
	a) -Djava.library.path is set to a folder containing shared libraries of an older LWJGL version.
	b) The classpath contains jar files of an older LWJGL version.
Possible solutions:
	a) Make sure to not set -Djava.library.path (it is not needed for developing with LWJGL 3) or make
	   sure the folder it points to contains the shared libraries of the correct LWJGL version.
	b) Check the classpath and make sure to only have jar files of the same LWJGL version in it.
[16:21:49] [Client thread/INFO]: [STDERR]: [LWJGL] [ERROR] Incompatible Java and native library versions detected.
Possible reasons:
	a) -Djava.library.path is set to a folder containing shared libraries of an older LWJGL version.
	b) The classpath contains jar files of an older LWJGL version.
Possible solutions:
	a) Make sure to not set -Djava.library.path (it is not needed for developing with LWJGL 3) or make
	   sure the folder it points to contains the shared libraries of the correct LWJGL version.
	b) Check the classpath and make sure to only have jar files of the same LWJGL version in it.
[16:21:49] [Client thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[16:21:49] [Client thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[16:21:49] [Client thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
ld-elf.so.1: /home/mike/lwjgl3/lwjgl3/bin/libs/liblwjgl.so: Undefined symbol "dcbNewCallback"

**Comment by johalun** [comment]
Maybe you need to run `pkg install dyncall`? To be honest I don't remember if that was provided by pkg or included in this repo.

**Comment by LordBSD** [comment]
Wow thanks for the fast response. Ill try it.

**Comment by LordBSD** [comment]
I got it to work man thanks. I dont know what exactly I did that fixed it, but I removed lwjgl that was in my system completely, and rebuilt your repo. I got minecraft working with BD resourcePacks 512MB, and optifine with shaders! its beautiful thank you!
