### ISSUE TITLE
No Permission for dependencies?

### ISSUE THREAD

**Issue by Centural-US** [johalun/lwjgl3-port#4]
When attempting to run the build script it presents me with this for each dependency it is attempting to download from github

Please make sure you have the correct access rights
and the repository exists.
Cloning into 'bimg'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

**Comment by johalun** [comment]
I guess you need to upload your public ssh key to github to use this way. If you don't have one you can change all the links in build.sh to use http. Example:
https://github.com/johalun/bimg

**Comment by Centural-US** [comment]
Thank you, I was just reading through the build script now and though that was going to be the plan. I appreciate the upload to git iv been needing lwjgl 3 for MC on FreeBSD for awhile now!

**Comment by johalun** [comment]
Having some issues on FreeBSD 13... Let me know how it goes for you. Hopefully we'll have a working version in ports soon!

**Comment by Centural-US** [comment]
I'm working on getting it running on Falcon, which from what I read is TrueOS (FreeBSD 1.13); Ill keep you posted on how it goes.

**Comment by Centural-US** [comment]
Looking into ld and what -lc is. This is where I am currently
```
/usr/local/bin/ld: cannot find -lc
    collect2: error: ld returned 1 exit status
    *** Error code 1

    Stop.
    make[1]: stopped in /usr/home/acg/Downloads/minecraft-client-1.13/openal-soft/build/CMakeFiles/CMakeTmp
    *** Error code 1

    Stop.
    make: stopped in /usr/home/acg/Downloads/minecraft-client-1.13/openal-soft/build/CMakeFiles/CMakeTmp




  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:5 (PROJECT)


-- Configuring incomplete, errors occurred!


```
