### ISSUE TITLE
Graphic issues on FreeBSD 13

### ISSUE THREAD

**Issue by johalun** [johalun/lwjgl3-port#5]
What work perfectly on 12-CURRENT seem to fail on 13-CURRENT. I experience two issues
- Jumping cause the view to swing heavily up and down. Disabling "view bobbing" fixes this.
- When moving the around in the inventory screen the avatar should follow the mouse cursor but instead is rotating 10x more than it should. After a second of moving the mouse the game freezes.

Updating all dependencies and lwjgl3 itself did not help. Experimenting now with building the updated repos on a clean 12-RELEASE system to see if the problem exist there.

**Comment by johalun** [comment]
Yeah, I found out the same after building on 12.0 as well.. I wonder if this is due to a change in the jar files minecraft downloads or a change in freebsd ports versions? Do anyone have an old working version of minecraft to test on a new freebsd installation (doing it offline of course to prevent minecraft from downloading updates)?

**Comment by michal800106** [comment]
Hi. I had the same issue and I’ve found that is connected with version of openjdk. After bumping to bootstrap openjdk 11 the problems have gone and the game is working correctly.

**Comment by johalun** [comment]
@michal800106  Hey! After a few months of being away from this, I rebuilt with same configuration on 13-current and bugs were gone. Didn't have to change anything. It works nice with 1.14 as well :D

**Comment by johalun** [comment]
Works with more recent version of 13.0-CURRENT. Closing.
